### ISSUE TITLE
🐛 Platform UI freezes when a general error happens

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1466]
## Describe the bug
When i used excel to save a comma-delimited list in a file, it automaticaally appended " to the string.  I only noticed once i opened it in a text editor: 

![image](https://user-images.githubusercontent.com/15824252/82393680-1f662500-9a15-11ea-89e7-e0c44e39e790.png)

Once you submit the file, this is the issue: 
![image](https://user-images.githubusercontent.com/15824252/82393429-5425ac80-9a14-11ea-9836-684a9e5504e1.png)
```
{,…}
data: {,…}
errors: [{message: "Cannot return null for non-nullable field ClinicalSubmissionSchemaError.message.",…}]
0: {message: "Cannot return null for non-nullable field ClinicalSubmissionSchemaError.message.",…}
extensions: {code: "INTERNAL_SERVER_ERROR", exception: {,…}}
code: "INTERNAL_SERVER_ERROR"
exception: {,…}
stacktrace: ["Error: Cannot return null for non-nullable field ClinicalSubmissionSchemaError.message.",…]
0: "Error: Cannot return null for non-nullable field ClinicalSubmissionSchemaError.message."
1: "    at completeValue (/appDir/node_modules/graphql/execution/execute.js:560:13)"
2: "    at completeValueCatchingError (/appDir/node_modules/graphql/execution/execute.js:495:19)"
3: "    at resolveField (/appDir/node_modules/graphql/execution/execute.js:435:10)"
4: "    at executeFields (/appDir/node_modules/graphql/execution/execute.js:275:18)"
5: "    at collectAndExecuteSubfields (/appDir/node_modules/graphql/execution/execute.js:713:10)"
6: "    at completeObjectValue (/appDir/node_modules/graphql/execution/execute.js:703:10)"
7: "    at completeValue (/appDir/node_modules/graphql/execution/execute.js:591:12)"
8: "    at completeValueCatchingError (/appDir/node_modules/graphql/execution/execute.js:495:19)"
9: "    at /appDir/node_modules/graphql/execution/execute.js:618:25"
10: "    at Array.forEach (<anonymous>)"
locations: [{line: 52, column: 7}]
0: {line: 52, column: 7}
message: "Cannot return null for non-nullable field ClinicalSubmissionSchemaError.message."
path: ["clinicalSubmissions", "clinicalEntities", 2, "schemaErrors", 0, "message"]
extensions: {tracing: {version: 1, startTime: "2020-05-20T01:03:57.903Z", endTime: "2020-05-20T01:03:58.027Z",…}}
```

This was my file:

```
program_id	submitter_donor_id	submitter_primary_diagnosis_id	age_at_diagnosis	cancer_type_code	basis_of_diagnosis	number_lymph_nodes_positive	number_lymph_nodes_examined	clinical_tumour_staging_system	clinical_stage_group	stage_suffix	clinical_t_category	clinical_n_category	clinical_m_category	presenting_symptoms	performance_status
DASH-CA	DASH-1	dashpd-1	51	C71.1	Clinical	2		Ann Arbor	Stage I						Grade 1
DASH-CA	DASH-2	dashpd-2	53	C50.2	Histology of a primary tumour	0		AJCC 8th Edition	Stage II		T1	N0	M0		Grade 0
DASH-CA	DASH-3	dashpd-3	28	C15.2		0		AJCC 8th Edition	Stage II		T2	N0	M0		Grade 0
DASH-CA	DASH-4	dashpd-4	19	C15.5		2		AJCC 8th Edition	Stage II		T4a	N1	M1		Grade 1
DASH-CA	DASH-5	dashpd-5	20	C25.1		0		AJCC 8th Edition	Stage III		T1	N0	M0		Grade 0
DASH-CA	DASH-6	dashpd-6	63	C25.1	Specific tumour markers	2		AJCC 8th Edition	Stage II		T1	N1	M0		Grade 0
DASH-CA	DASH-7	dashpd-7	56	C25.2	Specific tumour markers	6		AJCC 8th Edition	Stage III		T1	N2	M0		Grade 0
DASH-CA	DASH-8	dashpd-8	68	C25.9	Histology of a primary tumour	1		AJCC 8th Edition	Stage I		T1	N1	M0		Grade 0
DASH-CA	DASH-9	dashpd-9	37	C18.4		0		AJCC 8th Edition	Stage I		T2	N0	M0	Nausea	Grade 0
DASH-CA	DASH-10	dashpd-10	34	C18.9		0		AJCC 8th Edition	Stage IV		T1	N0	M0	"Nausea,Anemia"	Grade 1
```

## Expected behaviour
- On a destructive error, it should at least show the error on the page as a toast 
- The upload button should stop spinning and become re-enabled
-  the user should be able to continue uploading files.  Currently, you have to refresh the page to be able to upload.

**Comment by rosibaj** [comment]
@jaserud my files are all working now that we fixed the " bug - did you have a way to replicate this another way i can try out?
