### ISSUE TITLE
Add clear to the clinical submission

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#804]
- clear on files 
- clear on whole submission
- add success and failure toasts

**Comment by jaserud** [comment]
Note that you can still clear submission even if it is empty, because in backend the submission still exists. will be fixed after https://github.com/icgc-argo/argo-clinical/issues/205

**Comment by rosibaj** [comment]
👍 
- clear whole submission is working 
- clearing individual files is _not_ working.  I get no response on the ui (should at least get an error toast.  Seeing this error:
```
{
	"errors": [{
		"message": "No active submission data found for this program.",
		"locations": [],
		"path": ["clearClinicalSubmission"],
		"extensions": {
			"code": "BAD_USER_INPUT",
			"exception": {
				"error": "Error",
				"stacktrace": ["UserInputError: No active submission data found for this program.", "    at _callee$ (/usr/src/utils/restUtils.js:23:13)", "    at tryCatch (/usr/src/node_modules/regenerator-runtime/runtime.js:65:40)", "    at Generator.invoke [as _invoke] (/usr/src/node_modules/regenerator-runtime/runtime.js:303:22)", "    at Generator.prototype.<computed> [as next] (/usr/src/node_modules/regenerator-runtime/runtime.js:117:21)", "    at asyncGeneratorStep (/usr/src/utils/restUtils.js:10:103)", "    at _next (/usr/src/utils/restUtils.js:12:194)", "    at runMicrotasks (<anonymous>)", "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]
			}
		}
	}],
	"data": null,
	"extensions": {
		"tracing": {
			"version": 1,
			"startTime": "2019-11-07T00:01:18.983Z",
			"endTime": "2019-11-07T00:01:19.019Z",
			"duration": 35841071,
			"execution": {
				"resolvers": [{
					"path": ["clearClinicalSubmission"],
					"parentType": "Mutation",
					"fieldName": "clearClinicalSubmission",
					"returnType": "ClinicalSubmissionData!",
					"startOffset": 234012,
					"duration": 35587607
				}]
			}
		}
	}
}
```

**Comment by rosibaj** [comment]
individual clears are working now! thanks @jaserud !!!
